/**
 * Exercise-library metadata service.
 *
 * The library (876 exercises, generated by scripts/importFreeExerciseDB.ts) is
 * loaded on demand via a dynamic import so it lands in its own lazy chunk and
 * never touches the main bundle.
 *
 * Logged entries are keyed by exercise NAME (the legacy schema — see
 * docs/research/migration-spec.md), not by library id, so this module's job is
 * to resolve a logged name to library metadata. Resolution never renames or
 * rewrites anything the user has logged.
 */

export interface LibraryExercise {
  id: string;
  name: string;
  movement_pattern: string;
  /** Training style from the source data: "strength" | "stretching" | "cardio" | … */
  category: string;
  level: string;
  primary_muscles: string[];
  secondary_muscles: string[];
  equipment: string;
  execution_cues: string[];
  /**
   * Not present in the generated data — the importer deliberately omits it
   * rather than writing the same filler sentences onto all 876 entries.
   * Optional so consumers must handle its absence instead of crashing.
   */
  common_mistakes?: string[];
  default_setup: {
    supports_plate_calculator: boolean;
    bar_weight_lbs: number;
    is_unilateral: boolean;
    default_rest_seconds: number;
  };
  alternative_ids: string[];
  images: string[];
  /** Reserved for hand-authored synonyms; the generated data has none today. */
  aliases?: string[];
}

/**
 * This app's own exercise names → the library entry whose metadata best fits.
 *
 * Every legacy program name needs an entry: the library uses long descriptive
 * names ("Barbell Bench Press - Medium Grip"), so almost nothing matches by
 * accident. Approximate matches are marked — they exist to supply cues and
 * muscle data, not to claim the movements are identical.
 */
export const LEGACY_NAME_MAP: Record<string, string> = {
  // The 9 built-in program exercises.
  'Sumo Squats': 'Barbell Squat', // approximate: library has no wide-stance barbell squat
  Deadlifts: 'Barbell Deadlift',
  'Hip Thrust': 'Barbell Hip Thrust',
  'KB Swings': 'One-Arm Kettlebell Swings', // approximate: no two-hand swing in the library
  'Bench Press': 'Barbell Bench Press - Medium Grip',
  Rows: 'Bent Over Barbell Row',
  'Shoulder Press': 'Barbell Shoulder Press',
  'Lat Pulldown': 'Wide-Grip Lat Pulldown',
  'Leg Press / Lunges': 'Leg Press',
  // Common shorthand people type into custom exercises.
  'Glute Bridge': 'Barbell Glute Bridge',
  'Glute Bridges': 'Barbell Glute Bridge',
  Squat: 'Barbell Full Squat',
  Squats: 'Barbell Full Squat',
  RDL: 'Romanian Deadlift',
  RDLs: 'Romanian Deadlift',
};

let cachedLibrary: LibraryExercise[] | null = null;
/** In-flight load, so concurrent first callers share one fetch + parse. */
let loadPromise: Promise<LibraryExercise[]> | null = null;
let nameIndex: Map<string, LibraryExercise> | null = null;
/** Legacy map targets that no longer exist in the data (surfaced by tests). */
let unmappedLegacyTargets: string[] = [];

/** Lowercase, strip punctuation, collapse whitespace. "Pull-Up!" → "pull up". */
export function normalizeName(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/** Drops a trailing plural "s" from the last word: "deadlifts" → "deadlift". */
function singularize(normalized: string): string {
  return normalized.replace(/(\w+?)s$/, '$1');
}

function buildNameIndex(library: LibraryExercise[]): void {
  const index = new Map<string, LibraryExercise>();

  for (const item of library) {
    // Canonical name, then the id (ids are the name in snake_case).
    index.set(normalizeName(item.name), item);
    const idKey = normalizeName(item.id.replace(/_/g, ' '));
    if (!index.has(idKey)) index.set(idKey, item);
    for (const alias of item.aliases ?? []) {
      index.set(normalizeName(alias), item);
    }
  }

  // This app's names win over anything inferred above.
  const byName = new Map(library.map((e) => [normalizeName(e.name), e]));
  const missing: string[] = [];
  for (const [ourName, libraryName] of Object.entries(LEGACY_NAME_MAP)) {
    const target = byName.get(normalizeName(libraryName));
    if (target) index.set(normalizeName(ourName), target);
    else missing.push(`${ourName} -> ${libraryName}`);
  }
  unmappedLegacyTargets = missing;

  if (missing.length && import.meta.env.DEV) {
    // Silent no-ops are how a mapping table rots; say so loudly in dev.
    console.warn(
      `[exerciseLibrary] ${missing.length} LEGACY_NAME_MAP target(s) not found in the library:\n  ` +
        missing.join('\n  '),
    );
  }

  nameIndex = index;
}

/** Loads (once) and returns the whole library. */
export async function getExerciseLibrary(): Promise<LibraryExercise[]> {
  if (cachedLibrary) return cachedLibrary;
  if (loadPromise) return loadPromise;

  loadPromise = import('@/data/exerciseLibrary.json')
    .then((module) => {
      const library = module.default as unknown as LibraryExercise[];
      cachedLibrary = library;
      buildNameIndex(library);
      return library;
    })
    .catch((error: unknown) => {
      // Let the next caller retry rather than caching a permanent failure.
      loadPromise = null;
      throw error;
    });

  return loadPromise;
}

/**
 * Resolves a logged exercise name to library metadata.
 *
 * Tries, in order: the exact normalized name (including this app's mappings),
 * the singular form, then a prefix match — but only when exactly one library
 * entry matches, so an ambiguous guess returns nothing instead of the wrong
 * exercise.
 */
export function lookupExercise(logName: string): LibraryExercise | undefined {
  if (!nameIndex) return undefined;
  const key = normalizeName(logName);
  if (!key) return undefined;

  const exact = nameIndex.get(key);
  if (exact) return exact;

  const singular = nameIndex.get(singularize(key));
  if (singular) return singular;

  const prefixMatches: LibraryExercise[] = [];
  for (const [indexedName, exercise] of nameIndex) {
    if (indexedName.startsWith(key) && !prefixMatches.includes(exercise)) {
      prefixMatches.push(exercise);
      if (prefixMatches.length > 1) return undefined; // ambiguous — don't guess
    }
  }
  return prefixMatches[0];
}

/** Async form: loads the library first if it isn't in memory yet. */
export async function resolveExerciseMetadata(logName: string): Promise<LibraryExercise | undefined> {
  if (!nameIndex) await getExerciseLibrary();
  return lookupExercise(logName);
}

/** Library entries for an exercise's `alternative_ids`. */
export function alternativesFor(exercise: LibraryExercise): LibraryExercise[] {
  if (!cachedLibrary) return [];
  const byId = new Map(cachedLibrary.map((e) => [e.id, e]));
  return exercise.alternative_ids.map((id) => byId.get(id)).filter((e): e is LibraryExercise => Boolean(e));
}

/**
 * Curated library alternatives for a LOGGED exercise name, loading the library
 * if it is not in memory yet.
 *
 * 856 of the 876 library entries ship `alternative_ids` (about four each), so
 * this resolves hand-curated data rather than guessing at similarity. Returns
 * empty when the name does not resolve — `lookupExercise` refuses to guess on
 * an ambiguous prefix, and offering the wrong exercise is worse than offering
 * none.
 */
export async function libraryAlternativesFor(logName: string): Promise<LibraryExercise[]> {
  if (!logName.trim()) return [];
  const entry = await resolveExerciseMetadata(logName);
  return entry ? alternativesFor(entry) : [];
}

/** True once the library is in memory (lets render paths use the sync lookup). */
/**
 * The library IF it is already in memory, without triggering a load.
 *
 * For callers that only run after something else has awaited
 * `getExerciseLibrary()` — returning null rather than a promise keeps them
 * synchronous and keeps the 1.2 MB chunk from being fetched by a render.
 */
export function getLoadedLibrary(): LibraryExercise[] | null {
  return cachedLibrary;
}

export function isLibraryLoaded(): boolean {
  return cachedLibrary !== null;
}

/** Legacy map entries whose target is missing from the data. Asserted in tests. */
export function getUnmappedLegacyTargets(): string[] {
  return unmappedLegacyTargets;
}

/** Test seam — clears the module cache between cases. */
export function resetExerciseLibraryCache(): void {
  cachedLibrary = null;
  loadPromise = null;
  nameIndex = null;
  unmappedLegacyTargets = [];
}
